### ISSUE TITLE
Added test case for 401 being returned

### ISSUE THREAD

**Issue by dhaksddj** [masterjefferson/TwitchBoard#3]
[https://gist.github.com/dhaksddj/eb08577ecb62a15a99d7b24f7a506a10](gist)

I found the issue was the code was not handling the 401 so I added a test for it and did a parallel implementation to see if you liked it or not. Also, the test case was still finishing before the request so I added a CountdownLatch.

I couldn't create a PR or a new branch so I created the Gist above instead. Do I need to be granted access? I was getting 403.

I hope to join you today but may have to go out.

Edit: Not sure why the gist is 404 when i click it. Does it work for you?

**Comment by jeffypooo** [comment]
merged #4
